---

- set_fact:
    fname: "{{local_release_dir}}/{{download.dest}}"
  run_once: true
  when:
    - download.enabled
    - download_run_once
  tags:
    - facts

- name: file_download | copy file to ansible host
  synchronize:
    src: "{{ fname }}"
    dest: "{{ fname }}"
    use_ssh_args: "{{ has_bastion | default(false) }}"
    mode: pull
  delegate_to: localhost
  delegate_facts: no
  run_once: true
  become: false
  when:
    - download.enabled
    - download_run_once
    - inventory_hostname == download_delegate
    - download_delegate != "localhost"

- name: file_download | upload file to nodes
  synchronize:
    src: "{{ fname }}"
    dest: "{{ fname }}"
    use_ssh_args: "{{ has_bastion | default(false) }}"
    mode: push
  delegate_to: localhost
  delegate_facts: no
  become: false
  register: get_task
  until: get_task|succeeded
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
  when:
    - download.enabled
    - download_run_once
    - (inventory_hostname != download_delegate or
      download_delegate == "localhost")
  tags:
    - upload
    - upgrade
